// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg1AdSM8E1Bxr3ENjT5LBaoz5M6ya_zJY',
    appId: '1:594934755885:web:1cc27d5bb755645ee93ea4',
    messagingSenderId: '594934755885',
    projectId: 'chatapp-afcad',
    authDomain: 'chatapp-afcad.firebaseapp.com',
    storageBucket: 'chatapp-afcad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxkQRqTGfsGv3STzmgDE7U8xz9R97djN0',
    appId: '1:594934755885:android:60f88ed94d8de423e93ea4',
    messagingSenderId: '594934755885',
    projectId: 'chatapp-afcad',
    storageBucket: 'chatapp-afcad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrpxN4dh3vNWvGk0TdalzePXpFFVvW_m8',
    appId: '1:594934755885:ios:124e5f3bc8a1aa56e93ea4',
    messagingSenderId: '594934755885',
    projectId: 'chatapp-afcad',
    storageBucket: 'chatapp-afcad.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrpxN4dh3vNWvGk0TdalzePXpFFVvW_m8',
    appId: '1:594934755885:ios:4e1eaee8248b9efce93ea4',
    messagingSenderId: '594934755885',
    projectId: 'chatapp-afcad',
    storageBucket: 'chatapp-afcad.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
